package entity;
// Generated Apr 7, 2019 6:24:16 PM by Hibernate Tools 4.3.1


import java.util.Date;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="employee_5"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String recordNo;
     private String name;
     private int age;
     private String sex;
     private Date dob;
     private String remark;

    public User() {
    }

    public User(String recordNo, String name, int age, String sex, Date dob, String remark) {
       this.recordNo = recordNo;
       this.name = name;
       this.age = age;
       this.sex = sex;
       this.dob = dob;
       this.remark = remark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="RecordNo", nullable=false, length=45)
    public String getRecordNo() {
        return this.recordNo;
    }
    
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo;
    }

    
    @Column(name="Name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Age", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    
    @Column(name="Sex", nullable=false, length=45)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Dob", nullable=false, length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="Remark", nullable=false, length=45)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

   //This method writes the values of contact object with System.out.println(user.toString()) code  
    @Override  
    public String toString()  
    {  
        return "user" +  
            "\n\t RecordNo: " + this.recordNo +  
            "\n\t EmployeeName: " + this.name +  
            "\n\t Age: " + this.age +  
            "\n\t Sex: " + this.sex +  
            "\n\t Date of Birth: " + this.dob +  
            "\n\t Remark: " + this.remark;  
    }  
}  
